### PR TITLE
[Swift 3.0] Fix crash for looking up sim id on real device

### PR DESCRIPTION
**Pull request by kdawgwilk**
This fixes a crash when trying to lookup a simulator identifier on a real device. Fixes Issue #60

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Alright this is ready to go.  I found a better API to get the ENV var for the simulator that won't crash if it doesn't exist.  and I give a default "Unknown" value as the identifier because I tried the identifier passed in but it caused and infinite recursion :(

**Comment by dennisweissmann** [comment]
Hi @kdagwilk! Thank you so much for exploring and solving this! This is so much nicer (and obviously better) 💯. One small thing: this code doesn't compile (during the transition to Swift 3 we lowercased the enum cases, so it should be `simulator` (with a small "s"). If you could fix that and then CI hopefully passes, I will merge it :) thanks so much 🙏 This is awesome 👏 🎉

**Comment by dennisweissmann** [comment]
My comment from #61 applies here too, I think :( sorry for the trouble!

**Comment by dennisweissmann** [comment]
😔 sigh ... it's been ultra flaky for a few months now, LGTM, thanks! 🙏

**Pull request merged**
