### PR TITLE
Make Map and Identifier Public

### PR DESCRIPTION
**Pull request by KraigWastlund**
This is a great repo.
I needed to be able to compare with other devices and identifiers so I made the `identifier` and the `mapIdentifierToDevice` public.
No changes were made to your code, only increased the public api
I also added a unit test.
Thx.

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Hi Kraig, thank you very much! Can you briefly explain why you need the identifier? I'm just curious ...  Thing is, I think that the identifier is kind of an implementation detail ... Can you shortly explain your situation (why you need it)? That'd be super nice :)

Do you think a nicer solution would be to provide another initializer that takes an identifier? You could then create a device from an identifier and compare / etc. those.

**Comment by KraigWastlund** [comment]
Sure @dennisweissmann  
The reason I need access to the identifier is because the app I'm working on uses that identifier in the model to record what device the user was on when they performed a specific action.  

We have logs in our model that have a `device_type` property.  That type's value is the identifier.  
When we display that log later, we tell the user what action was performed and what device it was performed on.

Example of our log:  
__LOG__  
* id = uuid ex("ijfoaiwej3o23jijdf")
* proj_id = string ex("3iiji3imofw90m")
* equip_id = string ex("fji3ijfi900a3jn")
* action_type = int ex(10)
* `device_type = string` ex("iPhone3,1")
* updated_on = date ex(1472141086)
* updater_id = string ex("ifj3ij0vn398bji")

and so forth...  

Thank you for the consideration, I hope that answers your question.  
-Kraig

**Comment by dennisweissmann** [comment]
Hi Kraig,

Thanks so much for your thorough explanation! I thought a little bit more about the approach I explained earlier but I figured yours is easier (because the other device created would have the same battery / etc. stats as the real one). Merged, thanks again! :)

**Comment by KraigWastlund** [comment]
Awesome.  Thx for the quick responses and for the awesome pod.

**Pull request merged**
