### PR TITLE
Added known ppi values for applicable devices

### PR DESCRIPTION
**Pull request by piterwilson**

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Now that we have a (hopefully) pretty clean way to store specific device capabilities at compile time and generate the code from that, it'd be nice to have that :) @piterwilson  Are you interested in tackling this?

**Comment by piterwilson** [comment]
@dennisweissmann yeah sure! ill pull from your master and see what the 'generate' thing does.

**Comment by dennisweissmann** [comment]
Cool, thanks! :) If you have any questions feel free to ask!

**Comment by piterwilson** [comment]
@dennisweissmann I understand that you are using .gyb to automate some of the repetitive parts of the code. How do you render the gyb source into swift? are there usage instructions on utils/gyb or a resource on how this is setup?

**Comment by dennisweissmann** [comment]
Yah sure :) The transformation of the .gyb into .swift happens in an Xcode Build Phase (I called it "Generate Device", you can see it when you click on the project file inside Xcode, and then click on "Build Phases". In there you can find the "Generate Device" phase which looks like this:

```
./Utils/gyb --line-directive '' -o ./Source/Device.generated.swift ./Source/Device.swift.gyb
```

This tells the gyb script (also inside the repository, this comes originally from the apple/swift repository, the stdlib uses it a lot) to generate the code.

The syntax is the following:

Everything is taken as is, except for lines that start with a "%" (or blocks which start with "%{" and end with "}%", those are interpreted as python (or a subset/dialect?). So there you can create variables and loops and classes and stuff.

E.g.

```
% for device in iOSDevices:
    /// ${device.comment}
    ///
    /// ![Image](${device.imageURL})
    case ${device.caseName}
% end
```
This loops through a variable called `iOSDevices` (declared in line 67) and prints these 4 lines as they are (because there is no "%" at the front or a "%{"/"%}" block around them), and substituting (using the second (the interpolation) syntax:

```
${some.variable}
```

This allows us to refer to each of the device's properties in "output" code (i.e. the part of the code which is in the .swift file after the processing).

You can do quite complicated stuff with this, however, this is pretty much the first python I've ever written so it's probably pretty ugly and bad for people familiar with python 🙈...

What *I* would do is the following:

1. Extend the definition of the python class `Device`:

```
  def __init__(self, caseName, comment, imageURL, identifiers, diagonal, screenRatio, description, ppi):
    self.caseName = caseName
    self.comment = comment
    self.imageURL = imageURL
    self.identifiers = identifiers
    self.diagonal = diagonal
    self.screenRatio = screenRatio
    self.description = description
    self.ppi = ppi

```

2. Take a look at all the devices and extend them, e.g.

```
iPods = [
            Device("iPodTouch5",      "Device is an [iPod Touch (5th generation)](https://support.apple.com/kb/SP657)", "https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP657/sp657_ipod-touch_size.jpg",                ["iPod5,1"],                                  4,    (9, 16),  "iPod Touch 5"),
            Device("iPodTouch6",      "Device is an [iPod Touch (6th generation), 326](https://support.apple.com/kb/SP720)", "https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP720/SP720-ipod-touch-specs-color-sg-2015.jpg", ["iPod7,1"],                                  4,    (9, 16),  "iPod Touch 6", 326)
        ]
```

Note the "326" in the above code, that's the position of the ppi in the class's constructor.

This should hopefully work :)

That was just a very quick explanation, I haven't found a really good blog post or anything about it (maybe I should write one 🤔 I've always wanted to start a blog :D), so this is all self taught from experimentation and reading the stdlib ...

If you have further questions feel free to ask! :)

**Comment by piterwilson** [comment]
@dennisweissmann thanks for the detailed explanation. I was able to figure out the gyb syntax, i found it familiar from looking at the swift project's source code :) I think the approach is very suitable for this kind of library. I like your suggestion on the ppi implementation and will follow it.
 
For a while there i couldn't get the project to even run, and then i realised that it looks like you setup the project to use swift 4. I haven't migrated yet but i will write the code in swift 3 which should be good enough. 

Thanks and talk soon.

**Pull request closed without merging**
