### PR TITLE
Add boolean and array functions to check if the device has a sensor housing

### PR DESCRIPTION
**Pull request by Zandor300**
I added an array of devices that feature a sensor housing (aka a notch) and a Boolean function that tells whether or not the current device features a sensor housing.

### CODE REVIEW

**Comment by Zandor300** [comment]
@dennisweissmann what do you think of this addition?

**Comment by kudit** [comment]
Didn’t review the code, and this may not apply here, but note that the iPad Pro has a “sensor housing” that is contained in the notch of iPhone X but does not have a notch.

**Comment by Zandor300** [comment]
So, do you think it should be renamed to “hasNotch”? Weird, since Apple calls it a sensor housing all over it’s developer docs while I haven’t seen references link that for iPad...

**Comment by dennisweissmann** [comment]
Thanks for the mention @Zandor300, this triggered an email :)

I like the addition :) with regards to the naming: 

I think I like “notch” better, this is the first time I heard the term sensor housing (but that’s not a good enough reason to discard the term if it’s the right one describing the property) - I’ll leave that up to you though :) in any case I’d remove the “A” in `allDevicesWithA[SensorHousing | Notch]`.

Thank you @Zandor300 for contributing🙏 This is great :)

**Comment by Zandor300** [comment]
@dennisweissmann can't tell if you like or dislike the email notification caused by your mention. 🤔

I think keeping it as sensor housing is the best choice:

> Inset essential content to prevent clipping. In general, content should be centered and symmetrically inset so it looks great in any orientation, isn’t clipped by rounded corners, isn’t hidden by a **sensor housing**, and isn’t obscured by the indicator for accessing the Home screen. [...]

> Don't mask or call special attention to key display features. Don't attempt to hide a device's rounded corners, **sensor housing**, or indicator for accessing the Home screen by placing black bars at the top and bottom of the screen. [...]

Both from https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/

I will however rename the variable like you suggested.

**Comment by dennisweissmann** [comment]
I like the mention, sorry for not making that clearer :) I don’t know why but github doesn’t send me emails when someone opens a PR or an issue, only direct mentions cause an email ...

Alright, that seems reasonable to me, thanks for the rename and again for working on that 🎉

I’ll merge it but I can’t release it because I don’t have a MacBook right now ...

I’m also in the process of transferring this repo to a colleague, and maybe she can trigger a release sooner than I can.

Again, thank you for working on that, that’s great! :) 🙏🎉

**Pull request merged**
