### PR TITLE
Updated for Swift 3

### PR DESCRIPTION
**Pull request by rigobertomolina**
Updated DeviceKit for Swift 3 in branch swift-3

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Awesome! Thanks! Let's wait for CI to finish :)

**Comment by rigobertomolina** [comment]
Oh my God. All I did was edit the main file not anything else. I'm sorry this is my first pull request ever.

**Comment by dennisweissmann** [comment]
No worries :) That's perfectly fine :) We all have to get started :) Let me look into it!

**Comment by rigobertomolina** [comment]
Alright, thanks :)

**Comment by rigobertomolina** [comment]
Is it the fact that I didn't change this line `osx_image: xcode7.3` to `osx_image: xcode8.0` in .travis.yml?

**Comment by dennisweissmann** [comment]
Exactly! I wanted it to for you, but I don't have push access to your repository. Can you change it and try again?

**Comment by rigobertomolina** [comment]
Aww, failed again.

**Comment by dennisweissmann** [comment]
Nevermind! 👍 the Xcode 8 image on travis-ci does only come with iOS 10 simulators, so I had to change the simulators from 9.1 to 10.0. Let's hope this works :)

**Comment by rigobertomolina** [comment]
It failed again :(

**Comment by dennisweissmann** [comment]
Yeah, this time it's the pod file ... Man, swiftpm cannot come fast enough :D

**Comment by rigobertomolina** [comment]
Yeah I saw that when I pushed my commits, I didn't want to mess with anything inside the pod file

**Comment by dennisweissmann** [comment]
Yeah, I don't either :D Need to play around with it a little bit ... It says there's a new format, let's see ... Of course my ruby installation is broken again! Yuck!

**Comment by rigobertomolina** [comment]
I've used pods before, but never created one so I didn't know what to change, I need to start learning these things

**Comment by dennisweissmann** [comment]
I gave up! :D I just disabled the pod lib lint function for now ... Let's try it again!

**Comment by dennisweissmann** [comment]
This is ridiculous! :/ Yet another test ...

**Comment by rigobertomolina** [comment]
So complicated 😂

**Comment by dennisweissmann** [comment]
Okay this is getting to really bug me :/ Need to go to Uni now, I'll look into it later today ...

**Comment by rigobertomolina** [comment]
I'll try and look around, thanks though!

**Comment by dennisweissmann** [comment]
Thanks! I tried one last thing, let's see!

**Pull request closed without merging**
