### PR TITLE
Create allDevicesWithRoundedDisplayCorners and hasRoundedDisplayCorners variables.

### PR DESCRIPTION
**Pull request by Zandor300**
Create allDevicesWithRoundedDisplayCorners and hasRoundedDisplayCorners variables like suggested in https://github.com/dennisweissmann/DeviceKit/issues/159. Doesn't however implement the breaking changes that were also suggested there so the issue shouldn't be closed.

Would like to also implement a variable for getting the actual corner radius of the display but according to this StackOverflow answer, it isn't as simple as just setting `layer.cornerRadius`: https://apple.stackexchange.com/a/336499/277581

*(Additional commits are because I screwed up syncing my fork's master with upstream)*

### CODE REVIEW

**Comment by Zandor300** [comment]
@dennisweissmann sorry for yet another mail notification 😜

**Comment by Zandor300** [comment]
@dennisweissmann Also, I suggest creating a 2.0 branch to start working on that to solve some of the issues that have breaking changes? If you're going to do that, I would suggest waiting on releasing my previous changes to save it for 2.0.

**Comment by dennisweissmann** [comment]
Alright, I wanted to release an 2.0 with (at least) Swift 5.0, since that’s around the corner it makes sense to me.

This repo uses master as the dev branch, so I would be fine with committing whatever you want to master. If there is something we should backport to an 1.X version we could cherrypick. WDYT?

**Comment by Zandor300** [comment]
In that case, I'm fine with merging this pull request if you are.

Do you want me to already make some changes for 2.0, like fixing issues like https://github.com/dennisweissmann/DeviceKit/issues/149 and https://github.com/dennisweissmann/DeviceKit/issues/130 if I have some spare time this week?
I think its better to create a 2.0 branch for those changes but then have this pull request still be for a 1.x release.

**Pull request closed without merging**
