### PR TITLE
watchOS

### LINKED ISSUE #135: watchOS Support
Is there any particular reason why watchOS is not currently supported?

### PR DESCRIPTION
**Pull request by robbiet480**
This PR adds support for watchOS 4.0 and above.

Closes #135

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Thanks for kicking this off! 🎉🙏 if you need help you can ping me anytime!

**Comment by robbiet480** [comment]
@dennisweissmann Thanks! I left two comments for you on #135 which I could use feedback and help with.

**Comment by robbiet480** [comment]
Absolutely, cut the release!

**Comment by robbiet480** [comment]
🎉

**Comment by dennisweissmann** [comment]
I'll expand the readme in another PR (probably not today though, it's late here), would love to release a new version but first I have to install CocoaPods and all that (I recently wiped my MacBook ...)

**Pull request merged**
