### PR TITLE
Add disk space properties

### PR DESCRIPTION
**Pull request by jamesbebbington**
Hey @dennisweissmann following on from #48 , here's a quick first stab at adding disk space related properties. I'm not sure about the use of `disk` in the property names, seeing as spinning rust is becoming but a distant memory. The tests are pretty useless too but it's a start.

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Hey @jamesbebbington! Sorry for the huge delay, I've been on vacation 🏝. I like it :) I thought about introducing a property like `fileSystem` or something like that but it's not worth it because there's not really enough information that would justify an additional struct and the additional complexity coming with it. So I like it :) One minor thing though: Int64 is on all systems that support Swift and iOS/tvOS the same as Int, which is why I think we should use it, shouldn't we? Thanks for contributing! 🎉

**Comment by jamesbebbington** [comment]
Hey @dennisweissmann, sorry for the huge delay, I've been stuck working on other things of late.

> `Int64` is on all systems that support Swift and iOS/tvOS the same as `Int`, which is why I think we should use it, shouldn't we?

Yeah, that makes sense, though I'm relatively new to Cocoa programming so best to defer to you either way. I've updated the PR to use unsized `Int`s.

I'm not sure what you want to do with the tests, as I'm not sure how best to mock the `attributesOfFileSystem`, Dependancy Injection being somewhat tricky with `enum`s.

**Comment by dennisweissmann** [comment]
Perfect! 🎉Can you rebase so that we can get this merged? 🙏 I'll try to release 1.1.0 over the weekend and would love this to be part of it.

**Comment by jamesbebbington** [comment]
Good stuff. Rebased.

Any chance this could be released on the swift 2.3 branch too? Our app hasn't made the migration to swift 3 yet.

**Comment by dennisweissmann** [comment]
Thank you! Awesome 👏 I won't have the time to release a new version because I don't have a computer atm ... regarding Swift 2.3 🤔 I'm not sure, I officially dropped support for it but I guess dropping support doesn't necessarily mean there can't be stuff added, right? :D so if you have the time to create a PR I'll merge it :) thanks for your work! I really appreciate it!

I'll merge this as soon as it doesn't fail anymore on CI (even though I know it works it's impossible for me to merge otherwise because I'm mobile and GitHub doesn't allow that).

**Comment by jamesbebbington** [comment]
> regarding Swift 2.3 … if you have the time to create a PR I'll merge it :)

Sure no problem, I'll submit another PR for a version that supports swift 2.3.

> I'll merge this as soon as it doesn't fail anymore on CI

Is there anything for me do do for that? The failures don't look to be related to my patch.

Thanks!

**Comment by dennisweissmann** [comment]
Awesome, thank you! :)

No, the failures are Travis CI glitches, I noticed them starting with Xcode 8 betas ... I just have to restart them often enough, eventually all of them will pass ...

**Comment by jamesbebbington** [comment]
> regarding Swift 2.3 … if you have the time to create a PR I'll merge it :)

I had a stab at this the other day and found that unlike in 3.0, under 2.3 I needed to `import Foundation` to use `NSFileManager`. You seem to be doing quite fine-grained importing as I assume you're trying to avoid importing Foundation. Can you give me some pointers about what I should be importing instead?

**Comment by dennisweissmann** [comment]
That is weird! :O I mean it's weird that you don't have to import in Swift 3, it's not in the stdlib ... There's no particular reason why I use qualified imports, in the beginning I thought code completion would be better because much less is visible but that's, unfortunately, not true. We can import Foundation.FileManager in Swift 3 anyways (I assume it's a bug). And CI is still failing wth ... I restarted it like 20 times over the past days ...

**Comment by dennisweissmann** [comment]
I should actually look at the test failures 🙄 I thought they're flaky because they've always been, but his time it's different and tests are actually failing :) It's the test you added, so the usedDiscSize is sometimes not reported 🤔

**Comment by dennisweissmann** [comment]
Hey @jamesbebbington :)

Sorry it took me so long to come back to this :(

I've decided that I will finally merge this :)

Since the tests are still failing, could you remove them? :D I don't think they are necessary (at least in their current form) because the functions explicitly return an optional, so testing for a non-nil value doesn't make too much sense in my opinion ...

Thanks a ton for contributing and again sorry for the long delay.

**Pull request closed without merging**
