### PR TITLE
Fixed xcode 7.3 issue

### PR DESCRIPTION
**Pull request by phiren**
swift switch must be exhaustive consider adding a default clause

### CODE REVIEW

**Comment by dennisweissmann** [comment]
Hey @phiten, CI failed (you made the same changes as @cannyboy. Can you try to remove the .Unspecified case and replace it with `default: .Unspecified`?

**Comment by phiten** [comment]
I think you mean @phiren not me ;)

**Comment by phiren** [comment]
Make changes, please check

**Comment by dennisweissmann** [comment]
Sorry @phiten, I'm on mobile and don't have any kind of completion ... @phiren Thank you so much!! :) really appreciate your help! 🙏

**Comment by phiren** [comment]
Thank you for the DeviceKit, I find it's easiest way to determine device

**Comment by dennisweissmann** [comment]
That's nice to hear :) if spare time allows I'm planning to extending the functionality to include screen sizes and other properties, and to make it cross platform (adding OS X, watchOS, and eventually Linux (if that works, I have no idea :D)).

**Comment by phiren** [comment]
I will wait for watch is :)

**Pull request merged**
